#!/usr/bin/env python3
"""
Orchestrator for AI Employee

This script serves as the main coordinator for the AI Employee system,
managing the various components and workflows.
"""

import os
import sys
import time
import logging
import codecs
from pathlib import Path
from datetime import datetime

# Fix Windows console encoding
if sys.platform == 'win32':
    sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer, errors='replace')
    sys.stderr = codecs.getwriter('utf-8')(sys.stderr.buffer, errors='replace')

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('orchestrator.log', encoding='utf-8'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger('Orchestrator')

class AI_Employee_Orchestrator:
    """Main orchestrator for the AI Employee system."""

    def __init__(self, vault_path: str = "."):
        self.vault_path = Path(vault_path)
        self.folders = {
            'inbox': self.vault_path / 'Inbox',
            'needs_action': self.vault_path / 'Needs_Action',
            'done': self.vault_path / 'Done',
            'plans': self.vault_path / 'Plans',
            'pending_approval': self.vault_path / 'Pending_Approval',
            'logs': self.vault_path / 'Logs',
            'drop_folder': self.vault_path / 'Drop_Folder'
        }

        # Create required directories
        for folder in self.folders.values():
            folder.mkdir(exist_ok=True)

        logger.info("AI Employee Orchestrator initialized")
        logger.info(f"Vault path: {self.vault_path}")
        for name, path in self.folders.items():
            logger.info(f"{name}: {path}")

    def check_needs_action(self):
        """Check for items in Needs_Action folder."""
        needs_action_files = list(self.folders['needs_action'].glob('*.md'))
        logger.info(f"Found {len(needs_action_files)} items in Needs_Action")
        return needs_action_files

    def check_pending_approval(self):
        """Check for items awaiting approval."""
        pending_files = list(self.folders['pending_approval'].glob('*.md'))
        logger.info(f"Found {len(pending_files)} items pending approval")
        return pending_files

    def process_needs_action(self):
        """Process items in Needs_Action folder."""
        files = self.check_needs_action()

        if not files:
            logger.info("No items in Needs_Action to process")
            return

        logger.info(f"Processing {len(files)} items in Needs_Action")

        for file_path in files:
            logger.info(f"Processing: {file_path.name}")

            # In a real implementation, this would call Claude Code
            # to process the action file and create a plan
            self.create_plan_for_action(file_path)

    def create_plan_for_action(self, action_file: Path):
        """Create a plan file for the given action."""
        # Read the action file to get details (with encoding fallback)
        try:
            content = action_file.read_text(encoding='utf-8')
        except UnicodeDecodeError:
            # Fallback to default encoding (cp1252 on Windows)
            content = action_file.read_text()

        # Create a plan file name based on the action
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        plan_name = f"PLAN_{action_file.stem.replace('FILE_DROP_', '')}_{timestamp}.md"
        plan_path = self.folders['plans'] / plan_name

        # Create plan content
        plan_content = f"""---
created: {datetime.now().isoformat()}
status: pending
related_to: {action_file.name}
---

# Plan for Action: {action_file.stem}

## Objective
Process the action file {action_file.name} according to company guidelines.

## Action Items
- [ ] Review content of original file
- [ ] Apply company handbook rules
- [ ] Take appropriate action based on file type and content
- [ ] Update dashboard with status
- [ ] Move original action file to Done when complete

## Notes
This plan was automatically generated by the AI Employee Orchestrator.

Content of original action file:
{content[:500]}...  # First 500 characters of original file
"""

        # Write the plan file (with UTF-8 encoding)
        plan_path.write_text(plan_content, encoding='utf-8')
        logger.info(f"Created plan file: {plan_path.name}")

    def move_to_done(self, file_path: Path):
        """Move a file to the Done folder."""
        if file_path.exists():
            done_path = self.folders['done'] / file_path.name
            file_path.rename(done_path)
            logger.info(f"Moved {file_path.name} to Done folder")
            return done_path
        else:
            logger.warning(f"File {file_path} does not exist")
            return None

    def update_dashboard(self):
        """Update the dashboard with current status."""
        dashboard_path = self.vault_path / "Dashboard.md"

        if not dashboard_path.exists():
            logger.warning("Dashboard.md not found, skipping update")
            return

        # Count items in each folder
        inbox_count = len(list(self.folders['inbox'].glob('*')))
        needs_action_count = len(list(self.folders['needs_action'].glob('*')))
        done_count = len(list(self.folders['done'].glob('*')))

        # Read current dashboard content (with UTF-8 encoding)
        content = dashboard_path.read_text(encoding='utf-8')

        # Update stats section
        lines = content.split('\n')
        new_lines = []

        for line in lines:
            if line.startswith('- **Files in Inbox:**'):
                new_lines.append(f'- **Files in Inbox:** {inbox_count}')
            elif line.startswith('- **Tasks in Needs_Action:**'):
                new_lines.append(f'- **Tasks in Needs_Action:** {needs_action_count}')
            elif line.startswith('- **Completed Today:**'):
                new_lines.append(f'- **Completed Today:** {done_count}')
            elif line.startswith('- **Last Updated:**'):
                new_lines.append(f'- **Last Updated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}')
            elif line.startswith('- **Active Watchers:**'):
                # This would be updated based on actual running watchers
                new_lines.append('- **Active Watchers:** File System Watcher')
            else:
                new_lines.append(line)

        # Write updated content (with UTF-8 encoding)
        dashboard_path.write_text('\n'.join(new_lines), encoding='utf-8')
        logger.info("Dashboard updated")

    def run_once(self):
        """Run one cycle of the orchestrator."""
        logger.info("Starting orchestrator cycle")

        # Process any pending actions
        self.process_needs_action()

        # Update dashboard with current status
        self.update_dashboard()

        logger.info("Orchestrator cycle completed")

    def run_continuous(self, interval: int = 60):
        """Run the orchestrator continuously."""
        logger.info(f"Starting continuous orchestrator (checking every {interval}s)")

        try:
            while True:
                self.run_once()
                time.sleep(interval)
        except KeyboardInterrupt:
            logger.info("Orchestrator stopped by user")


def main():
    """Main function to run the orchestrator."""
    print("AI Employee Orchestrator")
    print("=" * 30)

    # Initialize orchestrator
    orchestrator = AI_Employee_Orchestrator()

    # Run one cycle for demonstration
    orchestrator.run_once()

    print("\nOrchestrator initialized successfully!")
    print("Folders created and ready for use.")
    print("\nTo run continuously: python orchestrator.py --continuous")

    # Check command line arguments
    import sys
    if len(sys.argv) > 1 and sys.argv[1] == "--continuous":
        print("\nStarting continuous mode...")
        orchestrator.run_continuous()


if __name__ == "__main__":
    main()